name: finsum_mobile
description: "A finance installment app with clean architecture"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  
  # Navigation
  go_router: ^14.6.2
  
  # Responsive UI
  flutter_screenutil: ^5.9.3
  
  # Network
  dio: ^5.7.0
  connectivity_plus: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # Dependency Injection
  get_it: ^8.0.2
  injectable: ^2.5.0
  
  # Environment
  flutter_dotenv: ^5.2.1
  
  # UI Components
  shimmer: ^3.0.0
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  
  # Localization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  # Utils
  mask_text_input_formatter: ^2.9.0
  pin_code_fields: ^8.0.1
  animate_do: ^3.3.4
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - .env
  
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Variable.ttf
